/**
 * Industry Profile Engine — dynamically configures the app per industry.
 * Adding a new industry = adding one entry. No existing code changes (OCP).
 * See: docs/01_PRD.md, docs/10_BUSINESS_RULES.md §11.2
 */
import type { ViewKey, ModulesConfig } from "@/lib/store";
import type { LucideIcon } from "lucide-react";
import { Store, Box, Factory, Pill, UtensilsCrossed, Scissors, Headset, Smartphone, Shirt, Car, Gem, Wrench, Stethoscope, ShoppingCart } from "lucide-react";

export type DashboardKPI = "sales" | "collected" | "outstanding" | "profit" | "purchases" | "expenses" | "customers" | "inventory_value" | "low_stock" | "pos_sales";

export interface QuickAction { key: string; label: string; view: ViewKey; params?: Record<string, unknown>; icon: LucideIcon; }

export interface IndustryProfile {
  id: string; label: string; icon: LucideIcon; description: string;
  modules: Partial<ModulesConfig>;
  inventoryMode: "inventory_heavy" | "service_heavy" | "no_inventory";
  dashboardKPIs: DashboardKPI[];
  quickActions: QuickAction[];
  invoiceTemplate: "detailed" | "compact" | "service";
  reports: string[];
  defaults?: { invoicePrefix?: string; barcodeEnabled?: boolean; expiryTracking?: boolean; batchTracking?: boolean; serialTracking?: boolean; };
}

const base: Partial<IndustryProfile> = { invoiceTemplate: "detailed" };

export const INDUSTRY_PROFILES: Record<string, IndustryProfile> = {
  retail: { ...base, id: "retail", label: "Retail Shop", icon: Store, description: "General retail & kirana", modules: { pos: true, inventory: true, gst: true, barcode: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "collected", "outstanding", "inventory_value"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Store }, { key: "pos", label: "POS Billing", view: "pos", icon: ShoppingCart }], reports: ["sales_register", "profit_loss", "inventory_valuation", "gst"], defaults: { invoicePrefix: "INV", barcodeEnabled: true } } as IndustryProfile,
  wholesale: { ...base, id: "wholesale", label: "Wholesale / Distributor", icon: Box, description: "Bulk trading & distribution", modules: { inventory: true, gst: true, barcode: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "outstanding", "purchases", "inventory_value"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Box }, { key: "new_purchase", label: "New Purchase", view: "purchases", icon: ShoppingCart }], reports: ["sales_register", "purchase_register", "profit_loss", "party_summary"], defaults: { invoicePrefix: "INV", barcodeEnabled: true } } as IndustryProfile,
  manufacturer: { ...base, id: "manufacturer", label: "Manufacturer", icon: Factory, description: "Production & assembly", modules: { inventory: true, gst: true, manufacturing: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "purchases", "inventory_value", "profit"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Factory }, { key: "new_purchase", label: "New Purchase", view: "purchases", icon: ShoppingCart }], reports: ["profit_loss", "inventory_valuation", "sales_register"], defaults: { invoicePrefix: "INV" } } as IndustryProfile,
  medical: { ...base, id: "medical", label: "Medical / Pharmacy", icon: Pill, description: "Pharmacy with expiry tracking", modules: { pos: true, inventory: true, gst: true, barcode: true, expiry: true, batch: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "collected", "low_stock", "inventory_value"], quickActions: [{ key: "pos", label: "POS Billing", view: "pos", icon: Pill }, { key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Store }], reports: ["sales_register", "inventory_valuation", "gst"], defaults: { invoicePrefix: "INV", barcodeEnabled: true, expiryTracking: true, batchTracking: true } } as IndustryProfile,
  restaurant: { ...base, id: "restaurant", label: "Restaurant / Café", icon: UtensilsCrossed, description: "F&B with POS", modules: { pos: true, inventory: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "pos_sales", "collected", "profit"], quickActions: [{ key: "pos", label: "POS Billing", view: "pos", icon: UtensilsCrossed }], invoiceTemplate: "compact", reports: ["sales_register", "profit_loss", "day_book"], defaults: { invoicePrefix: "BILL" } } as IndustryProfile,
  salon: { ...base, id: "salon", label: "Salon / Spa", icon: Scissors, description: "Appointments & services", modules: { pos: true, crm: true }, inventoryMode: "service_heavy", dashboardKPIs: ["sales", "collected", "customers", "profit"], quickActions: [{ key: "pos", label: "New Bill", view: "pos", icon: Scissors }], invoiceTemplate: "service", reports: ["sales_register", "profit_loss", "party_summary"], defaults: { invoicePrefix: "SRV" } } as IndustryProfile,
  service: { ...base, id: "service", label: "Service Business", icon: Headset, description: "Service invoices", modules: { gst: true }, inventoryMode: "no_inventory", dashboardKPIs: ["sales", "collected", "outstanding", "profit"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Headset }], invoiceTemplate: "service", reports: ["sales_register", "profit_loss", "party_summary"], defaults: { invoicePrefix: "INV" } } as IndustryProfile,
  electronics: { ...base, id: "electronics", label: "Electronics / Mobile", icon: Smartphone, description: "Serial number tracking", modules: { pos: true, inventory: true, gst: true, barcode: true, serial: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "collected", "low_stock", "inventory_value"], quickActions: [{ key: "pos", label: "POS Billing", view: "pos", icon: Smartphone }, { key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Store }], reports: ["sales_register", "inventory_valuation", "gst"], defaults: { invoicePrefix: "INV", barcodeEnabled: true, serialTracking: true } } as IndustryProfile,
  garments: { ...base, id: "garments", label: "Garments / Apparel", icon: Shirt, description: "Sizes & variants", modules: { pos: true, inventory: true, gst: true, barcode: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "collected", "inventory_value", "low_stock"], quickActions: [{ key: "pos", label: "POS Billing", view: "pos", icon: Shirt }], reports: ["sales_register", "inventory_valuation", "gst"], defaults: { invoicePrefix: "INV", barcodeEnabled: true } } as IndustryProfile,
  automobile: { ...base, id: "automobile", label: "Automobile Parts", icon: Car, description: "Spare parts trading", modules: { inventory: true, gst: true, barcode: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "purchases", "outstanding", "inventory_value"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Car }, { key: "new_purchase", label: "New Purchase", view: "purchases", icon: ShoppingCart }], reports: ["sales_register", "purchase_register", "inventory_valuation"], defaults: { invoicePrefix: "INV", barcodeEnabled: true } } as IndustryProfile,
  jewellery: { ...base, id: "jewellery", label: "Jewellery", icon: Gem, description: "High-value invoicing", modules: { pos: true, inventory: true, gst: true, barcode: true, serial: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "collected", "inventory_value", "profit"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Gem }], reports: ["sales_register", "profit_loss", "inventory_valuation", "gst"], defaults: { invoicePrefix: "INV", barcodeEnabled: true, serialTracking: true } } as IndustryProfile,
  hardware: { ...base, id: "hardware", label: "Hardware Store", icon: Wrench, description: "Tools & hardware retail", modules: { pos: true, inventory: true, gst: true, barcode: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "collected", "low_stock", "inventory_value"], quickActions: [{ key: "pos", label: "POS Billing", view: "pos", icon: Wrench }], reports: ["sales_register", "inventory_valuation", "gst"], defaults: { invoicePrefix: "INV", barcodeEnabled: true } } as IndustryProfile,
  clinic: { ...base, id: "clinic", label: "Clinic / Healthcare", icon: Stethoscope, description: "Patient consultations", modules: { crm: true, gst: true }, inventoryMode: "no_inventory", dashboardKPIs: ["sales", "collected", "customers", "profit"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: Stethoscope }], invoiceTemplate: "service", reports: ["sales_register", "profit_loss", "party_summary"], defaults: { invoicePrefix: "INV" } } as IndustryProfile,
  fmcg: { ...base, id: "fmcg", label: "FMCG Distribution", icon: ShoppingCart, description: "Fast-moving consumer goods", modules: { inventory: true, gst: true, barcode: true, batch: true }, inventoryMode: "inventory_heavy", dashboardKPIs: ["sales", "purchases", "outstanding", "inventory_value"], quickActions: [{ key: "new_invoice", label: "New Invoice", view: "sales", params: { action: "new" }, icon: ShoppingCart }, { key: "new_purchase", label: "New Purchase", view: "purchases", icon: Box }], reports: ["sales_register", "purchase_register", "profit_loss", "inventory_valuation"], defaults: { invoicePrefix: "INV", barcodeEnabled: true, batchTracking: true } } as IndustryProfile,
};

export const INDUSTRY_LIST = Object.values(INDUSTRY_PROFILES);
export function getIndustryProfile(id: string | null | undefined): IndustryProfile { return INDUSTRY_PROFILES[id || "retail"] || INDUSTRY_PROFILES.retail; }
export function getIndustryModules(id: string | null | undefined): ModulesConfig {
  const p = getIndustryProfile(id);
  return { pos: false, inventory: false, gst: false, payroll: false, crm: false, manufacturing: false, expiry: false, batch: false, serial: false, barcode: false, onlineStore: false, ...p.modules };
}
export function getIndustryKPIs(id: string | null | undefined): DashboardKPI[] { return getIndustryProfile(id).dashboardKPIs; }
export function getIndustryQuickActions(id: string | null | undefined): QuickAction[] { return getIndustryProfile(id).quickActions; }
